services:
  school_db:
    image: postgres:latest
    container_name: school_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
