export * from "./aluno";
export * from "./aula";
export * from "./instrumento";
export * from "./matricula";
export * from "./pertence";
export * from "./professor";
export * from "./toca";
export * from "./turma";
export * from "./utiliza";
